//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Enrollment = new HashSet<Enrollment>();
        }
    
        public int CourseID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Credits { get; set; }
    
        public virtual ICollection<Enrollment> Enrollment { get; set; }
    }
}
